FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Disable ESLint in dev for faster startup
ENV NEXT_LINT_WARNONLY=true

# Copy source code
COPY . .

# Expose dev server port
EXPOSE 3000

# Run dev server
CMD ["yarn", "dev", "-H", "0.0.0.0"]