/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { TOOLS_AND_SOFTWARES } from '@/config/constant';
import { ReactElement } from 'react';
import { PublicLayout } from '@/layouts/public-layout';
import { Link } from '@/components/link';
import profilePhoto from '../../public/me.jpeg';
import ArticleItems from '@/components/widgets/article-cards/article-items';

const Home = function () {
  return (
    <>
      <Head>
        <title>Shittu Muhammed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-slate-700 dark:text-slate-200">
        <div className="container md:max-w-6xl px-4 md:px-0 mx-auto ">
          <section>
            <div className="container md:max-w-6xl flex flex-col items-center py-10 md:py-16 mx-auto md:flex-row">
              <div className="flex flex-col items-start text-left lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 animate-slide-in-left">
                {/* <h2 className="mb-8 text-xs font-semibold tracking-widest uppercase title-font">
                {' '}
                Hi, I &apos;m{' '}
              </h2> */}
                <h1 className="mb-4 md:mb-8 text-6xl font-black tracking-tighter md:text-8xl">
                  Muhammed Shittu{' '}
                </h1>
                <h3 className="mb-4 md:mb-8 text-4xl font-bold tracking-tighter md:text-5xl text-cyan-800 dark:text-cyan-400 ">
                  Full Stack Software Engineer{' '}
                </h3>
                <p className="mb-8 md:text-2xl leading-relaxed text-left">
                  {' '}
                  I&apos;m passionate about collaborating with talented individuals to create
                  outstanding software.
                  {/* I'm passionate about crafting innovative and high-performance web
                  applications using my skills in FullStack development, cloud technologies, and
                  automated testing to deliver outstanding results that exceed expectations. */}
                </p>
                <div className="flex flex-col justify-center lg:flex-row ">
                  <Link
                    href="#"
                    text="LinkedIn"
                    icon={
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        className="flex-shrink-0 w-6 h-6 transition duration-75 dark:text-gray-400 "
                      >
                        <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
                        <rect x="2" y="9" width="4" height="12" />
                        <circle cx="4" cy="4" r="2" />
                      </svg>
                    }
                  />
                </div>
              </div>
              <div className="w-full lg:w-1/3 lg:max-w-lg md:w-1/2 hidden md:block  animate-swing-in-right-fwd">
                <Image
                  width={600}
                  height={720}
                  className="object-cover object-center rounded-lg"
                  src={profilePhoto}
                  alt="me"
                  priority
                />
              </div>
            </div>
          </section>
          <section className="py-20 md:py-24">
            <div className="flex md:flex-row flex-col justify-between gap-5">
              <div className="section-body w-full md:w-1/2">
                <div className=" relative float-left hidden md:block">
                  {/* <Image
                    width={112}
                    height={112}
                    className="mb-0x w-14 h-14 md:w-28 md:h-28 rounded-full mr-3 md:mr-6"
                    src="https://dummyimage.com/128x128/F3F4F7/8693ac"
                    alt="product designer"
                  /> */}
                  <Image
                    className="mb-0x w-14 h-14 md:w-28 md:h-28 rounded-full mr-3 md:mr-6"
                    src={profilePhoto}
                    alt="Muhammed Shittu"
                  />
                </div>
                <h2 className="text-5xl md:text-8xl font-extrabold ">
                  I build{' '}
                  <span className="text-cyan-800 dark:text-cyan-400"> delightful products</span>
                </h2>
              </div>
              <div className=" w-full md:w-5/12 text-lg md:text-xl leading-relaxed text-justify">
                <p>
                  A dynamic engineer with 2 years of experience building outstanding web
                  applications and optimizing code for peak performance, proficient in a wide range
                  of languages and frameworks.
                </p>{' '}
                <div className="grid grid-cols-2 md:max-w-xs mt-10 lg:mb-0 mb-6 w-10/12 gap-10">
                  <a
                    target="_blank"
                    href="https://linkedin.com/in/muhammedshittu"
                    className="flex items-center font-normal rounded-lg"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="w-6 h-6"
                    >
                      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
                      <rect x="2" y="9" width="4" height="12" />
                      <circle cx="4" cy="4" r="2" />
                    </svg>
                    <span className="flex-1 ml-3 whitespace-nowrap">LinkedIn</span>
                  </a>
                  <a
                    target="_blank"
                    href="https://twitter.com/devshittu"
                    className="flex items-center font-normal rounded-lg"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      className="w-6 h-6"
                    >
                      <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z" />
                    </svg>
                    <span className="flex-1 ml-3 whitespace-nowrap">Twitter</span>
                  </a>
                  <a
                    target="_blank"
                    href="mailto:mshittu.work@gmail.com"
                    className="flex items-center font-normal rounded-lg"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      className="w-6 h-6"
                    >
                      <circle cx="12" cy="12" r="4" />
                      <path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-3.92 7.94" />
                    </svg>
                    <span className="flex-1 ml-3 whitespace-nowrap">Email</span>
                  </a>
                  <a
                    target="_blank"
                    href="#"
                    className="flex items-center font-normal rounded-lg"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      className="h-6 w-6"
                    >
                      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                      <polyline points="14 2 14 8 20 8" />
                      <line x1="16" y1="13" x2="8" y2="13" />
                      <line x1="16" y1="17" x2="8" y2="17" />
                      <polyline points="10 9 9 9 8 9" />
                    </svg>
                    <span className="flex-1 ml-3 whitespace-nowrap">Resume</span>
                  </a>
                </div>
              </div>
            </div>
          </section>

          {/* Articles */}
          <section className="py-20">
            <div className="section-heading">
              <h1 className="text-6xl font-bold">Projects</h1>
              <p className="md:w-8/12 mt-4 mr-auto">
                My work largely revolves on the front-end with Vue/Nuxt.js, React/Next.js &
                TypeScript, Backend with and Node.js, Laravel and Django. Here are some of the
                projects I have worked on to showcase my skills:
              </p>
            </div>
            <div className="section-body mt-12">
              <div className="bg-slate-600">
                <div className="lg:grid lg:grid-cols-2">
                  <div className="py-24 px-10 lg:px-0 max-w-3xl lg:max-w-md mx-auto">
                    <h2 className="text-4xl tracking-tight font-extrabold">
                      <span className="block">Ready to dive in?</span>
                      <span className="block">Start your free trial today.</span>
                    </h2>
                    <p className="text-gray-300 mt-5">
                      Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                      Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                      when an unknown printer took a galley of type and scrambled it to make a type
                      specimen book.
                    </p>
                    <div className="inline-block shadow mt-5">
                      <a
                        href="#"
                        className="inline-block py-3 px-4 bg-white hover:bg-indigo-100 text-indigo-500 font-medium border border-transparent rounded-md"
                      >
                        Sign up for free
                      </a>
                    </div>
                  </div>
                  <div className="lg:relative lg:mt-16">
                    {/* https://images.pexels.com/photos/2559941/pexels-photo-2559941.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260 */}
                    <Image
                      className="lg:absolute lg:inset-0 h-60 w-full lg:h-full object-cover object-center lg:rounded-tl-md"
                      src="https://dummyimage.com/1260x750/F3F4F7/8693ac"
                      alt="Woman workcation on the beach"
                      width={1260}
                      height={750}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Articles */}
          <section className="py-20">
            <div className="section-heading">
              <h1 className="text-6xl font-bold">Articles I've written</h1>
              <p className="md:w-8/12 mt-4 mr-auto">
                I have gained valuable insights and learned important lessons through my experience
                as a full stack software developer, and I'm excited to share them with you through
                my writing. Whether you're a beginner or an experienced developer, my goal is to
                provide clear, concise, and practical insights that can help you improve your skills
                and build better apps. Check out some of my articles below and share with others.
              </p>
            </div>
            <div className="section-body mt-12">
              <ArticleItems />
              <Link
                href="https://mshittu.hashnode.dev/"
                className=" font-semibold py-2 text-cyan-400  text-smx  mt-6 inline-flex items-center group"
              >
                <p> View all </p>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4 ml-1 stroke-2 group-hover:translate-x-2 delay-100 duration-200 ease-in-out"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M9 5l7 7-7 7"
                  />
                </svg>
              </Link>
            </div>
          </section>
          {/* Tools and Features */}
          <section className="border-t border-slate-300  py-24">
            <div className="section-heading">
              <h1 className="text-6xl font-bold">Tools & Software</h1>
              <p className="md:w-8/12 mt-4 mr-auto">
                Over the years, I had the opportunity to work with various software, tools and
                frameworks. Here are some of them:
              </p>
            </div>
            <div className="section-body mt-12">
              <ul className="list-none flex flex-colx lg:flex-row flex-wrap md:w-10/12 mt-4 -mx-4 text-3xl md:text-3xl  text-cyan-800 dark:text-cyan-400">
                {TOOLS_AND_SOFTWARES.map((tool, i) => (
                  <li key={i}>
                    <a target="_blank" className={`flex items-center font-normal rounded-lg`}>
                      <span className={` flex-1 whitespace-nowrap m-4`}>{tool}</span>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </section>
          {/* Subscribe */}
          {/* <!-- COMPONENT CODE --> */}
          <section className="w-full rounded-lg">
            <div className="md:mx-auto py-24  border-t border-slate-300">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
                <div className=" ">
                  <h1 className="font-bold text-4xl">Stay up to date </h1>
                  <p className="text-lg mt-8">
                    Get emails from me about web development, tech, and early access to new
                    projects.
                  </p>
                </div>
                <div className="md:py-2 md:mx-4 lg:py-10">
                  <div className="rounded-full bg-white shadow flex w-full">
                    <input
                      type="text"
                      placeholder="Enter your email to join our mailing list"
                      className="w-full rounded-tl-full rounded-bl-full py-2 px-4"
                    />
                    <button className="bg-gray-400 rounded-tr-full rounded-br-full py-2 px-4">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        className="h-6 w-6 text-white"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z"
                        />
                      </svg>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* <!-- COMPONENT CODE --> */}
        </div>
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <PublicLayout>{page}</PublicLayout>;
};

export default Home;
